package server

const adminHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NoraMusic 主题商店</title>
<style>
:root{color-scheme:dark;--bg:#111318;--panel:#1b1f27;--line:#303744;--text:#eef1f6;--muted:#a8b0be;--accent:#9ee37d;--danger:#ff8f8f}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#111318,#18221b);font:15px system-ui,sans-serif;color:var(--text)}main{max-width:1180px;margin:0 auto;padding:32px 18px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}h1{font-size:28px;margin:0}h2{font-size:19px;margin:0 0 14px}.muted{color:var(--muted)}.panel{background:rgba(27,31,39,.9);border:1px solid var(--line);border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 30px #0003}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.stat{padding:16px;background:#202632;border-radius:10px}.stat strong{font-size:28px;display:block;color:var(--accent)}button{border:0;border-radius:8px;padding:9px 13px;background:var(--accent);color:#152012;font-weight:700;cursor:pointer}button.secondary{background:#323b49;color:var(--text)}button.danger{background:#542d35;color:#ffd1d1}button:disabled{opacity:.5;cursor:not-allowed}input{background:#10131a;color:var(--text);border:1px solid var(--line);padding:10px;border-radius:8px;width:100%;margin:6px 0 12px}label{display:block;color:var(--muted)}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.hidden{display:none}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-weight:500}.pill{display:inline-block;border-radius:999px;padding:3px 9px;background:#303a48;color:#d7e2f2;font-size:12px}.error{color:#ffacac;margin-top:10px}.ok{color:var(--accent);margin-top:10px}nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}small{color:var(--muted)}@media(max-width:680px){main{padding:20px 12px}th:nth-child(3),td:nth-child(3){display:none}}
</style></head><body><main><header><div><small>NORA / THEME STORE</small><h1>主题商店管理</h1></div><div id="identity" class="muted"></div></header><section id="auth" class="panel"><h2 id="auth-title">管理员登录</h2><form id="auth-form"><label>邮箱<input name="email" type="email" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" minlength="12" required></label><button>登录</button></form><p><button class="secondary" id="switch-register" type="button">首次启动？创建管理员</button></p><div id="auth-msg" class="error"></div></section><section id="app" class="hidden"><nav><button data-page="dashboard">仪表盘</button><button data-page="themes">主题库</button><button data-page="audit">审计记录</button><button data-page="settings">安全设置</button><button class="secondary" id="logout">退出</button></nav><div id="view"></div></section></main>
<script>
const $=s=>document.querySelector(s), api=async(path,opt={})=>{const res=await fetch('/admin/v1/'+path,{credentials:'same-origin',...opt,headers:{...(opt.headers||{}),'Accept':'application/json'}});const body=await res.json().catch(()=>({}));if(!res.ok)throw Error(body.error?.code||'请求失败');return body.data};let csrf='';let page='dashboard';
function msg(t,ok=false){$('#auth-msg').className=ok?'ok':'error';$('#auth-msg').textContent=t}
async function enter(){const s=await api('auth/session');csrf=s.csrfToken||'';$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#identity').textContent=s.email;if(!s.mfaEnabled&&location.protocol==='https:'){showMFASetup();}else load(page)}
async function showMFASetup(){const v=$('#view');v.innerHTML='<div class="panel"><h2>需要启用双因素认证</h2><p class="muted">公网模式要求管理员绑定验证器。点击生成密钥后，用任意 TOTP 验证器录入，再填写当前 6 位验证码。</p><button id="mfa-start">生成绑定密钥</button><div id="mfa-box"></div></div>';$('#mfa-start').onclick=async()=>{try{const x=await api('auth/mfa/setup',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:'{}'});$('#mfa-box').innerHTML='<p>密钥：<code>'+esc(x.secret)+'</code></p><p class="muted">'+esc(x.otpauthUri)+'</p><input id="mfa-code" inputmode="numeric" maxlength="6" placeholder="当前 6 位验证码"><button id="mfa-verify">完成绑定</button>';$('#mfa-verify').onclick=async()=>{try{await api('auth/verify-mfa',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:JSON.stringify({code:$('#mfa-code').value})});load(page)}catch(e){alert(e.message)}}}catch(e){alert(e.message)}}}
async function login(e){e.preventDefault();try{await api('auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});await enter()}catch(e){msg(e.message)}}
async function register(e){e.preventDefault();try{await api('auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});msg('管理员已创建，请登录',true);showLogin()}catch(e){msg(e.message)}}
function showLogin(){ $('#auth-title').textContent='管理员登录';$('#auth-form').innerHTML='<label>邮箱<input name="email" type="email" required></label><label>密码<input name="password" type="password" minlength="12" required></label><button>登录</button>';$('#auth-form').onsubmit=login }
function showRegister(){ $('#auth-title').textContent='创建管理员';$('#auth-form').innerHTML='<label>邮箱<input name="email" type="email" required></label><label>密码<input name="password" type="password" minlength="12" required></label><button>创建并登录</button>';$('#auth-form').onsubmit=register }
async function load(p){page=p;const v=$('#view');v.innerHTML='<div class="panel">读取中…</div>';try{if(p==='dashboard'){const d=await api('dashboard');v.innerHTML='<div class="grid">'+[['主题',d.themes],['已发布',d.publishedThemes],['草稿',d.drafts],['存储字节',d.storageBytes]].map(x=>'<div class="stat"><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>').join('')+'</div><div class="panel"><p class="muted">部署模式：'+d.mode+' · 主题访问：'+d.themeAccess+' · 离线策略：'+d.offlinePolicy+'</p></div>'}else if(p==='themes'){const d=await api('themes');v.innerHTML='<div class="panel"><div class="row"><h2 style="margin-right:auto">主题库</h2><input id="file" type="file" accept=".noratheme,.zip" style="max-width:260px"><button id="upload">上传主题</button></div><table><thead><tr><th>主题</th><th>最新版本</th><th>状态</th><th>操作</th></tr></thead><tbody>'+d.items.map(x=>'<tr><td><strong>'+esc(x.name)+'</strong><br><small>'+esc(x.package_id)+'</small></td><td>'+esc(x.latest_version||'—')+'<br><small>'+x.version_count+' 个版本</small></td><td><span class="pill">'+(x.deleted?'已删除':esc(x.latest_status||'—'))+'</span></td><td>'+(!x.deleted&&x.latest_status==='draft'?'<button data-act="publish" data-id="'+x.id+'" data-v="'+x.latest_version+'">发布</button> ':'')+(!x.deleted&&x.published_version?'<button class="secondary" data-act="withdraw" data-id="'+x.id+'" data-v="'+x.published_version+'">撤回</button> ':'')+(!x.deleted?'<button class="danger" data-act="delete" data-id="'+x.id+'">删除</button> ':'')+(x.deleted?'<button data-act="restore" data-id="'+x.id+'">恢复</button>':'')+'</td></tr>').join('')+'</tbody></table></div>';$('#upload').onclick=upload}else if(p==='audit'){const d=await api('audit-events');v.innerHTML='<div class="panel"><h2>审计记录</h2><table><thead><tr><th>操作</th><th>目标</th><th>时间</th></tr></thead><tbody>'+d.items.map(x=>'<tr><td>'+esc(x.action)+'</td><td>'+esc(x.target)+'</td><td>'+esc(x.createdAt)+'</td></tr>').join('')+'</tbody></table></div>'}else{const d=await api('settings');v.innerHTML='<div class="panel"><h2>安全与部署</h2><p>部署模式：<b>'+d.deployment.mode+'</b></p><p>监听地址：<code>'+esc(d.deployment.listenAddr)+'</code></p><p>主题访问：<b>'+d.policy.themeAccess+'</b> · 离线策略：<b>'+d.policy.offlinePolicy+'</b></p><p class="muted">部署环境变量修改后需要重启服务。</p></div><div class="panel"><h2>脚本 Token</h2><button id="token-create">创建 Token</button><div id="token-list" class="muted">读取中…</div></div>';loadTokens()}}catch(e){v.innerHTML='<div class="panel error">'+esc(e.message)+'</div>'}}
async function loadTokens(){try{const d=await api('auth/tokens');$('#token-list').innerHTML=d.items.map(x=>'<p><span class="pill">'+esc(x.name)+'</span> '+esc(x.createdAt)+' <button class="danger" data-token="'+x.id+'">撤销</button></p>').join('')||'还没有 Token'}catch(e){$('#token-list').textContent=e.message}}
document.addEventListener('click',async e=>{if(e.target.id==='token-create'){const name=prompt('Token 名称');if(name)try{const x=await api('auth/tokens',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({name})});alert('请立即保存 Token：\n'+x.token);loadTokens()}catch(err){alert(err.message)}}if(e.target.dataset.token){try{await api('auth/tokens/'+e.target.dataset.token,{method:'DELETE',headers:{'X-CSRF-Token':csrf}});loadTokens()}catch(err){alert(err.message)}}});
async function upload(){const f=$('#file').files[0];if(!f)return alert('请选择 .noratheme 文件');const body=new FormData();body.append('file',f);try{await api('themes/uploads',{method:'POST',headers:{'X-CSRF-Token':csrf},body});alert('上传成功，已保存为草稿');load('themes')}catch(e){alert(e.message)}}
document.addEventListener('click',async e=>{const b=e.target;if(b.dataset.page)load(b.dataset.page);if(b.id==='logout'){await api('auth/logout',{method:'POST',headers:{'X-CSRF-Token':csrf}});location.reload()}if(b.id==='switch-register')showRegister();if(b.dataset.act){const id=b.dataset.id,act=b.dataset.act;try{let path='themes/'+id+'/'+act,body={};if(act==='publish'||act==='withdraw'){body.version=b.dataset.v}else if(act==='delete'){path='themes/'+id;await fetch('/admin/v1/'+path,{method:'DELETE',headers:{'X-CSRF-Token':csrf}});return load('themes')}await api(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});load('themes')}catch(e){alert(e.message)}}});function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
(async()=>{try{const b=await fetch('/admin/v1/auth/bootstrap').then(r=>r.json());if(b.data?.setupRequired)showRegister();else{try{await enter()}catch{showLogin()}}}catch{showLogin()}})();
</script></body></html>`
